[package]
name = "juste"
version = "0.0.2"
edition = "2024"
license = "GPL-3.0"
authors = ["Effendi Saputra <effendi.saputra01@gmail.com>"]
description = "Brutalist UI engine."
readme = "README.md"
repository = "https://github.com/Hoyoll/juste"

[dependencies]
num-traits = "0.2.19"
